### ISSUE TITLE
Error creating UI from `substrate-ui-new`: Cannot find module '../lib/utils/unsupported.js'

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate-ui#13]
```
Shawns-MBP:substrate-bare shawntabrizi$ substrate-ui-new substrate
Cloning into 'substrate-ui'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 426 (delta 85), reused 76 (delta 42), pack-reused 303
Receiving objects: 100% (426/426), 4.58 MiB | 816.00 KiB/s, done.
Resolving deltas: 100% (288/288), done.
~/Desktop/substrate-bare ~/Desktop/substrate-bare
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
~/Desktop/substrate-bare
Shawns-MBP:substrate-bare shawntabrizi$ 
```

**Comment by shawntabrizi** [comment]
Issue seems unrelated to substrate, and more of a problem with Node.
