### ISSUE TITLE
Build is not compatible with node v12

### ISSUE THREAD

**Issue by jiayaoqijia** [paritytech/substrate-ui#37]
When building the code with the latest version of Node.js say v12.10.0, some libraries couldn't be built (below). 

``` make: *** [Release/obj.target/addon/src/blake2.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jiayaoqi/github/substrate-package/hello-ui/node_modules/blake2js
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
```

**Comment by jiayaoqijia** [comment]
A quick fix is to downgrade Node.js to v11 as below. 

```
npm install -g n   # Install n globally
n 11.15.0          # Install and use v11.15.0
```
